apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app001
  template:
    metadata:
      labels:
        app: app001
    spec:
      containers:
      - name: app001
        image: localhost:32000/codingsoldier/app001:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 10011
---
apiVersion: v1
kind: Service
metadata:
  name: service-app001
spec:
  selector:
    app: app001
  # 使用NodePort类型的Service，绑定service的10005端口到宿主机，以便在物理机上调用
  type: NodePort 
  ports: 
  - name: http
    port: 10011
    targetPort: 10011
#   暴露端口取值范围是30000-32767
    nodePort: 30011
