apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app002
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app002
  template:
    metadata:
      labels:
        app: app002
    spec:
      containers:
      - name: app002
        image: localhost:32000/codingsoldier/app002:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 10012
---
apiVersion: v1
kind: Service
metadata:
  name: service-app002
spec:
  selector:
    app: app002
  # 使用NodePort类型的Service，绑定service的10005端口到宿主机，以便在物理机上调用
  type: NodePort
  ports:
  - name: http
    port: 10012
    targetPort: 10012
#   暴露端口取值范围是30000-32767
    nodePort: 30012
